
OUTPUT_COLUMNS = [
    "tracking_id",
    "Region",
    "State",
    "shipperName",
    "sender_company",
    "sender_province",
    "sender_city",
    "sender_address",
    "Driver",
    "Hub",
    "Contractor",
    "Route_name",
    "Route_type",
    "has_customer_service",
    "created_time",
    "first_scanned_time",
    "last_scanned_time",
    "out_for_delivery_time",
    "attempted_time",
    "failed_route",
    "delivered_time",
    "success_route",
    "创建到入库时间",
    "库内停留时间",
    "尝试配送时间",
    "送达时间",
    "整体配送时间",
]

I18N = {
    "zh": {
        "language_label": "语言 / Language",
        "app_title": "Fimile美区运单运营数据分析系统",
        "version": "版本号：{version}",
        "route_info": "Driver / Hub / Contractor 将从 Route Name 自动解析：HUB-路区号-日期-DSP-司机名",
        "input_section": "1) 输入 Tracking IDs",
        "input_mode": "输入方式",
        "mode_db": "数据库按日期",
        "mode_file": "上传文件",
        "mode_text": "文本粘贴",
        "mode_text_db": "文本粘贴 + 数据库按日期",
        "start_date": "起始日期 (Created_at)",
        "end_date": "结束日期 (Created_at)",
        "load_btn": "从数据库加载运单号",
        "load_merge_btn": "从数据库加载并合并",
        "loading_db": "查询数据库中...",
        "no_tracking_found": "该日期范围内未找到任何 tracking_number",
        "db_preview": "数据库返回运单号预览（前 50 / 共 {count}）",
        "upload_file": "上传 CSV 或 XLSX",
        "paste_ids": "粘贴 Tracking IDs（支持换行/逗号/空格分隔）",
        "duplicate_ids": "重复 Tracking IDs",
        "fetch_section": "2) 调用 API 并导出",
        "fetch_btn": "Fetch / Export",
        "state_region_fail": "读取 State/Region 数据失败，将导出为空值：{error}",
        "processing": "处理中：{completed}/{total} - {tracking_id}",
        "done": "处理完成",
        "filter_view": "筛选视图",
        "hide_unknown_btn": "隐藏未知 DSP/Hub",
        "show_unknown_btn": "显示未知 DSP/Hub",
        "invalid_route_section": "Route_name 不符合标准",
        "invalid_route_empty": "全部 Route_name 均符合标准。",
        "pickup_section": "Pick up 路由（不计入妥投率统计）",
        "pickup_empty": "当前没有 Pick up 路由。",
        "download_pickup": "下载 Pick up 明细",
        "ofd_filter_start": "出库配送时间起始日期 (Out for Delivery)",
        "ofd_filter_end": "出库配送时间结束日期（不含当天） (Out for Delivery, Exclusive)",
        "apply_ofd_filter": "应用出库配送时间筛选",
        "customer_summary_section": "取货仓库分布",
        "customer_name": "客户名",
        "pickup_warehouse": "取货仓库",
        "state_group": "州",
        "shipping_address": "收货地址",
        "package_count": "包裹数",
        "download_customer_summary": "下载取货仓库表格",
        "scope": "范围",
        "nationwide": "全美",
        "customer_summary_empty": "当前筛选条件下暂无客户地址数据。",
        "all": "ALL",
        "success_count": "成功数量",
        "fail_count": "失败数量",
        "request_fail": "以下 tracking_id 请求失败",
        "download_fail_csv": "下载失败列表 CSV",
        "result_preview": "结果预览",
        "download_csv": "下载 CSV",
        "download_report": "下载数据报表（百分比+图表）",
        "report_dep_missing": "当前环境缺少图表报表依赖，无法导出整合报表。",
        "pod_review": "POD审核测试",
        "delivered": "已妥投",
        "no_delivered": "暂无已妥投运单。",
        "delivered_date": "妥投日期（Delivered Date）",
        "tracking_id": "运单号（Tracking ID）",
        "beans_link": "Beans 运单查询（查看 POD）",
        "compliant": "是否标记为合规",
        "open_beans": "打开 Beans 查看 POD",
        "kpi_title": "3) 时效与质量 KPI 图表",
        "layout_mode_label": "KPI 布局模式",
        "layout_mode_detailed": "详细模式（周/月）",
        "layout_mode_compact": "简略模式（日）",
        "compact_title": "24小时核心指标（日）",
        "daily_created_chart": "按创建日期统计包裹总数",
        "daily_delivered_chart": "按妥投日期统计包裹总数",
        "daily_eval_weight_chart": "按日期统计包裹评价重量",
        "compact_eval_weight": "所选包裹评价重量",
        "eval_weight_empty": "暂无可用评分数据",
        "kpi_empty": "暂无数据，无法计算 KPI。",
        "lost_detail": "丢包明细",
        "download_lost": "下载丢包明细",
        "download_delivered": "下载妥投率明细",
        "download_scan": "下载上网率明细",
        "lost_empty": "当前无符合丢包条件的运单。",
        "lost_no_scan": "没有 Last Scan 数据，无法计算月丢包率。",
    },
    "en": {
        "language_label": "语言 / Language",
        "app_title": "Fimile US Shipment Operations Dashboard",
        "version": "Version: {version}",
        "route_info": "Driver / Hub / Contractor are auto-parsed from Route Name: HUB-Route-Date-DSP-Driver",
        "input_section": "1) Input Tracking IDs",
        "input_mode": "Input Method",
        "mode_db": "Database by Date",
        "mode_file": "Upload File",
        "mode_text": "Paste Text",
        "mode_text_db": "Paste Text + Database by Date",
        "start_date": "Start Date (Created_at)",
        "end_date": "End Date (Created_at)",
        "load_btn": "Load Tracking IDs from DB",
        "load_merge_btn": "Load and Merge from DB",
        "loading_db": "Querying database...",
        "no_tracking_found": "No tracking numbers found in this date range",
        "db_preview": "DB Tracking Preview (Top 50 / Total {count})",
        "upload_file": "Upload CSV or XLSX",
        "paste_ids": "Paste Tracking IDs (newline/comma/space separated)",
        "duplicate_ids": "Duplicate Tracking IDs",
        "fetch_section": "2) API Fetch and Export",
        "fetch_btn": "Fetch / Export",
        "state_region_fail": "Failed to load State/Region data. Export will contain empty values: {error}",
        "processing": "Processing: {completed}/{total} - {tracking_id}",
        "done": "Completed",
        "filter_view": "Filter View",
        "hide_unknown_btn": "Hide Unknown DSP/Hub",
        "show_unknown_btn": "Show Unknown DSP/Hub",
        "invalid_route_section": "Invalid Route_name",
        "invalid_route_empty": "All Route_name values are compliant.",
        "pickup_section": "Pick up routes (excluded from delivery-rate KPI)",
        "pickup_empty": "No Pick up routes in current data.",
        "download_pickup": "Download Pick up details",
        "ofd_filter_start": "Out for Delivery Start Date",
        "ofd_filter_end": "Out for Delivery End Date (Exclusive)",
        "apply_ofd_filter": "Apply Out for Delivery date filter",
        "customer_summary_section": "Pickup Warehouse Distribution",
        "customer_name": "Customer",
        "pickup_warehouse": "Pickup Warehouse",
        "state_group": "State",
        "shipping_address": "Shipping Address",
        "package_count": "Package Count",
        "download_customer_summary": "Download pickup warehouse table",
        "scope": "Scope",
        "nationwide": "Nationwide",
        "customer_summary_empty": "No customer/address data under current filters.",
        "all": "ALL",
        "success_count": "Success Count",
        "fail_count": "Failure Count",
        "request_fail": "The following tracking IDs failed",
        "download_fail_csv": "Download Failed List CSV",
        "result_preview": "Result Preview",
        "download_csv": "Download CSV",
        "download_report": "Download Data Report (Percentages + Charts)",
        "report_dep_missing": "Chart/report dependency is missing in current environment; combined report export is unavailable.",
        "pod_review": "POD Review",
        "delivered": "Delivered",
        "no_delivered": "No delivered waybills.",
        "delivered_date": "Delivered Date",
        "tracking_id": "Tracking ID",
        "beans_link": "Beans Tracking Lookup (View POD)",
        "compliant": "Marked as Compliant",
        "open_beans": "Open Beans POD",
        "kpi_title": "3) KPI Charts: Timeliness & Quality",
        "layout_mode_label": "KPI Layout Mode",
        "layout_mode_detailed": "Detailed (Week/Month)",
        "layout_mode_compact": "Compact (Day)",
        "compact_title": "24h Core Metrics (Daily)",
        "daily_created_chart": "Daily package count by created date",
        "daily_delivered_chart": "Daily package count by delivered date",
        "daily_eval_weight_chart": "Daily package evaluation weight",
        "compact_eval_weight": "Selected package evaluation weight",
        "eval_weight_empty": "No score data available",
        "kpi_empty": "No data available to calculate KPI.",
        "lost_detail": "Lost Package Details",
        "download_lost": "Download Lost Details",
        "download_delivered": "Download Delivery Rate Details",
        "download_scan": "Download Scan Rate Details",
        "lost_empty": "No waybills match the lost-package condition.",
        "lost_no_scan": "No Last Scan data, monthly lost-package rate cannot be calculated.",
    },
}