
OUTPUT_COLUMNS = [
    "tracking_id",
    "Region",
    "State",
    "Hub",
    "Contractors",
    "Drivers",
    "Route_names",
    "Weight",
    "Volume",
    "Dim_weight",
    "Billable_weight",
    "Price",
    "sender_company",
    "sender_province",
    "sender_city",
    "sender_address",
    "created_time",
    "first_scanned_time",
    "last_scanned_time",
    "delivered_time",
    "entered_costomer_service",
    "beans_pod_link",
    "Route_type",
    "Intervals",
    "Is_delivered",
]

I18N = {
    "zh": {
        "language_label": "语言 / Language",
        "language_zh": "中文",
        "language_en": "English",
        "app_title": "Fimile美区运单运营数据分析系统",
        "version": "版本号：{version}",
        "route_info": "Driver / Contractor / Hub 直接基于 router_messages 中的 listRouteId 关联 assignee 信息；不再依赖 Route Name 或 scanned_at 逻辑判断。",
        "input_section": "1) 输入 Tracking IDs",
        "input_mode": "输入方式",
        "mode_db": "数据库按日期",
        "mode_file": "上传文件",
        "mode_text": "文本粘贴",
        "mode_text_db": "文本粘贴 + 数据库按日期",
        "start_date": "起始日期",
        "end_date": "结束日期",
        "date_filter_type": "日期筛选方式",
        "date_filter_created": "按照创建日期",
        "date_filter_delivery": "按照派送日期",
        "load_btn": "从数据库加载运单号",
        "load_merge_btn": "从数据库加载并合并",
        "report_filter_title": "报表时间筛选（按日期，可选）",
        "report_filter_start_label": "起始时间 - 日期",
        "report_filter_end_label": "截止时间 - 日期",
        "compute_metrics_btn": "计算数据",
        "compute_metrics_prompt": "数据已加载完成。请先设置筛选条件（可选），再点击“计算数据”生成各项指标。",
        "compute_metrics_applied_caption": "当前计算使用的筛选条件：{filters}",
        "report_filter_empty": "未设置筛选条件（按全量已加载数据计算）",
        "report_filter_invalid": "起始时间不能晚于截止时间。",
        "exclude_atl_wdr_toggle": "是否去除 WDR 和 ATL（默认开启）",
        "test_preset_notice": "测试用预设已启用：启动后自动设置起始日期 {start}、结束日期 {end}，并自动执行一次“从数据库加载并合并”。",
        "loading_db": "查询数据库中...",
        "no_tracking_found": "该日期范围内未找到任何 tracking_number",
        "db_preview": "数据库返回运单号预览（前 50 / 共 {count}）",
        "upload_file": "上传 CSV 或 XLSX",
        "paste_ids": "粘贴 Tracking IDs（支持换行/逗号/空格分隔）",
        "duplicate_ids": "重复 Tracking IDs",
        "fetch_section": "2) 从数据库读取并导出",
        "fetch_btn": "Fetch / Export",
        "state_region_fail": "读取 State/Region 数据失败，将导出为空值：{error}",
        "processing": "处理中：{completed}/{total} - {tracking_id}",
        "done": "处理完成",
        "filter_view": "筛选视图",
        "hide_unknown_btn": "隐藏未知 DSP/Hub",
        "show_unknown_btn": "显示未知 DSP/Hub",
        "override_hub_dropdown_label": "选择 Hub",
        "override_contractor_input_label": "填写 Contractor 名称",
        "override_contractor_input_placeholder": "例如：DSP01",
        "override_apply_btn": "应用",
        "override_apply_success": "已应用：{hub} 的 Unknown Contractor 已替换为 {contractor}",
        "override_apply_validation": "请选择 Hub 并填写 Contractor 名称后再应用。",
        "override_applied_title": "已应用替换规则",
        "route_attempts_section": "按派送尝试整理的 Route 明细",
        "route_attempts_empty": "暂无符合条件的 Route 派送尝试记录。",
        "route_attempts_unresolved_section": "未能归入 Route 的包裹",
        "multi_route_tracking_section": "单号跨 Route 派送明细",
        "multi_route_tracking_empty": "暂无单个 tracking_id 跨多个 Route 的派送记录。",
        "route_attempts_unresolved_empty": "所有包裹都已成功归入 Route。",
        "route_attempts_canceled_section": "取消/拦截件",
        "route_attempts_canceled_empty": "暂无取消/拦截件。",
        "route_attempts_lost_section": "丢件（OFD 后无 success/fail）",
        "route_attempts_lost_empty": "暂无符合条件的丢件。",
        "invalid_route_section": "Route_name 未匹配到已配置 Contractor",
        "invalid_route_empty": "全部 Route_name 均匹配到已配置 Contractor。",
        "pickup_section": "Pick up 路由（不计入妥投率统计）",
        "pickup_empty": "当前没有 Pick up 路由。",
        "download_pickup": "下载 Pick up 明细",
        "ofd_filter_start": "出库配送时间起始日期 (Out for Delivery)",
        "ofd_filter_end": "出库配送时间结束日期（不含当天） (Out for Delivery, Exclusive)",
        "apply_ofd_filter": "应用出库配送时间筛选",
        "delivery_filter_start": "delivery start date",
        "delivery_filter_end": "delivery end date",
        "apply_delivery_filter": "应用",
        "apply_filters": "应用筛选",
        "reset_filters": "重置筛选",
        "delivery_filter_invalid": "Delivery 开始日期不能晚于结束日期。",
        "timeliness_quality_breakdown_title": "时效与质量分层明细",
        "customer_summary_section": "取货仓库分布",
        "customer_name": "客户名",
        "pickup_warehouse": "取货仓库",
        "state_group": "州",
        "shipping_address": "收货地址",
        "package_count": "包裹数",
        "download_customer_summary": "下载取货仓库表格",
        "scope": "范围",
        "nationwide": "全美",
        "customer_summary_empty": "当前筛选条件下暂无客户地址数据。",
        "all": "ALL",
        "success_count": "成功数量",
        "fail_count": "失败数量",
        "request_fail": "以下 tracking_id 请求失败",
        "download_fail_csv": "下载失败列表 CSV",
        "result_preview": "结果预览",
        "download_csv": "下载 CSV",
        "download_report": "下载数据报表（百分比+图表）",
        "report_export_failed": "报表导出失败：{error}",
        "pod_review": "POD审核测试",
        "delivered": "已妥投",
        "no_delivered": "暂无已妥投运单。",
        "delivered_date": "妥投日期（Delivered Date）",
        "tracking_id": "运单号（Tracking ID）",
        "beans_link": "Beans 运单查询（查看 POD）",
        "compliant": "是否标记为合规",
        "open_beans": "打开 Beans 查看 POD",
        "kpi_title": "3) 时效与质量 KPI 图表",
        "layout_mode_label": "KPI 布局模式",
        "layout_mode_detailed": "详细模式（周/月）",
        "layout_mode_compact": "简略模式（日）",
        "compact_title": "24小时DSP考核数据（日）",
        "daily_created_chart": "按创建日期统计包裹总数",
        "daily_eval_weight_chart": "按日期统计包裹评价重量",
        "weight_bucket_chart": "重量段分布",
        "compact_eval_weight": "所选包裹评价重量",
        "eval_weight_empty": "暂无可用评分数据",
        "kpi_empty": "暂无数据，无法计算 KPI。",
        "lost_detail": "丢包明细",
        "download_lost": "下载丢包明细",
        "download_delivered": "下载妥投率明细",
        "download_dsp_detail": "下载DSP明细",
        "download_dsp_contractor_label": "选择 Contractor",
        "download_dsp_contractor_placeholder": "请先选择 Contractor",
        "download_dsp_requires_contractor": "下载 DSP 明细前必须先选择一个 Contractor。",
        "download_dsp_empty": "当前 Contractor 在所选日期范围内没有派送成功的单号。",
        "task_ready": "准备开始…",
        "task_done": "处理完成",
        "task_load_merge": "从数据库加载并合并",
        "task_compute_metrics": "开始计算",
        "task_prepare_dsp": "下载DSP报表",
        "task_step_assignee_cache": "下载并缓存 Assignee list",
        "task_step_router_messages": "加载 router_messages",
        "task_step_route_metadata": "构建 route / assignee 映射",
        "task_step_receiver_data": "读取收件地址信息",
        "task_step_sender_data": "读取发件地址信息",
        "task_step_tracking_rows": "合并运单结果",
        "task_step_validate_filters": "校验筛选条件",
        "task_step_apply_filters": "应用报表时间筛选",
        "task_step_build_route_attempts": "构建 Route 尝试明细",
        "task_step_prepare_exports": "准备导出数据",
        "task_step_collect_dsp_price": "补充 DSP Price 相关数据",
        "task_step_build_dsp_file": "生成 DSP Excel 文件",
        "download_dsp_prepare_btn": "生成DSP明细文件",
        "download_dsp_ready": "DSP 明细文件已生成，请点击下方按钮下载。",
        "download_scan": "下载上网率明细",
        "lost_empty": "当前无符合丢包条件的运单。",
        "lost_no_scan": "没有 Last Scan 数据，无法计算月丢包率。",
    },
    "en": {
        "language_label": "Language",
        "language_zh": "Chinese",
        "language_en": "English",
        "app_title": "Fimile US Shipment Operations Dashboard",
        "version": "Version: {version}",
        "route_info": "Driver / Contractor / Hub are resolved from router_messages listRouteId plus assignee metadata, without relying on Route Name or scanned_at hub inference.",
        "input_section": "1) Input Tracking IDs",
        "input_mode": "Input Method",
        "mode_db": "Database by Date",
        "mode_file": "Upload File",
        "mode_text": "Paste Text",
        "mode_text_db": "Paste Text + Database by Date",
        "start_date": "Start Date",
        "end_date": "End Date",
        "date_filter_type": "Date Filter Type",
        "date_filter_created": "By Created Date",
        "date_filter_delivery": "By Delivery Date",
        "load_btn": "Load Tracking IDs from DB",
        "load_merge_btn": "Load and Merge from DB",
        "report_filter_title": "Report Time Filter (Date, Optional)",
        "report_filter_start_label": "Start Time - Date",
        "report_filter_end_label": "End Time - Date",
        "compute_metrics_btn": "Calculate Metrics",
        "compute_metrics_prompt": "Data loading is complete. Set optional filters and click 'Calculate Metrics' to generate KPI outputs.",
        "compute_metrics_applied_caption": "Current calculation uses: {filters}",
        "report_filter_empty": "No filters applied (calculated from all loaded data)",
        "report_filter_invalid": "Start time cannot be later than end time.",
        "exclude_atl_wdr_toggle": "Exclude WDR and ATL (enabled by default)",
        "test_preset_notice": "Test preset enabled: on startup it auto-sets start date {start}, end date {end}, and auto-runs 'Load and Merge from DB' once.",
        "loading_db": "Querying database...",
        "no_tracking_found": "No tracking numbers found in this date range",
        "db_preview": "DB Tracking Preview (Top 50 / Total {count})",
        "upload_file": "Upload CSV or XLSX",
        "paste_ids": "Paste Tracking IDs (newline/comma/space separated)",
        "duplicate_ids": "Duplicate Tracking IDs",
        "fetch_section": "2) DB Read and Export",
        "fetch_btn": "Fetch / Export",
        "state_region_fail": "Failed to load State/Region data. Export will contain empty values: {error}",
        "processing": "Processing: {completed}/{total} - {tracking_id}",
        "done": "Completed",
        "filter_view": "Filter View",
        "hide_unknown_btn": "Hide Unknown DSP/Hub",
        "show_unknown_btn": "Show Unknown DSP/Hub",
        "override_hub_dropdown_label": "Select Hub",
        "override_contractor_input_label": "Enter Contractor name",
        "override_contractor_input_placeholder": "e.g. DSP01",
        "override_apply_btn": "Apply",
        "override_apply_success": "Applied: Unknown Contractor in {hub} is replaced with {contractor}",
        "override_apply_validation": "Please select a hub and enter a contractor name before applying.",
        "override_applied_title": "Applied replacement rules",
        "route_attempts_section": "Route details grouped by delivery attempts",
        "route_attempts_empty": "No route delivery-attempt records available.",
        "route_attempts_unresolved_section": "Packages not grouped into any route",
        "multi_route_tracking_section": "Tracking IDs delivered across multiple routes",
        "multi_route_tracking_empty": "No tracking IDs found with attempts across multiple routes.",
        "route_attempts_unresolved_empty": "All packages were grouped into routes successfully.",
        "route_attempts_canceled_section": "Canceled / intercepted packages",
        "route_attempts_canceled_empty": "No canceled/intercepted packages.",
        "route_attempts_lost_section": "Lost packages (no success/fail after OFD)",
        "route_attempts_lost_empty": "No packages match the lost-package rule.",
        "invalid_route_section": "Route_name with unmatched configured contractors",
        "invalid_route_empty": "All Route_name values matched configured contractors.",
        "pickup_section": "Pick up routes (excluded from delivery-rate KPI)",
        "pickup_empty": "No Pick up routes in current data.",
        "download_pickup": "Download Pick up details",
        "ofd_filter_start": "Out for Delivery Start Date",
        "ofd_filter_end": "Out for Delivery End Date (Exclusive)",
        "apply_ofd_filter": "Apply Out for Delivery date filter",
        "delivery_filter_start": "delivery start date",
        "delivery_filter_end": "delivery end date",
        "apply_delivery_filter": "Apply",
        "apply_filters": "Apply Filters",
        "reset_filters": "Reset Filters",
        "delivery_filter_invalid": "Delivery start date cannot be later than end date.",
        "timeliness_quality_breakdown_title": "Timeliness & Quality Breakdown",
        "customer_summary_section": "Pickup Warehouse Distribution",
        "customer_name": "Customer",
        "pickup_warehouse": "Pickup Warehouse",
        "state_group": "State",
        "shipping_address": "Shipping Address",
        "package_count": "Package Count",
        "download_customer_summary": "Download pickup warehouse table",
        "scope": "Scope",
        "nationwide": "Nationwide",
        "customer_summary_empty": "No customer/address data under current filters.",
        "all": "ALL",
        "success_count": "Success Count",
        "fail_count": "Failure Count",
        "request_fail": "The following tracking IDs failed",
        "download_fail_csv": "Download Failed List CSV",
        "result_preview": "Result Preview",
        "download_csv": "Download CSV",
        "download_report": "Download Data Report (Percentages + Charts)",
        "report_export_failed": "Report export failed: {error}",
        "pod_review": "POD Review",
        "delivered": "Delivered",
        "no_delivered": "No delivered waybills.",
        "delivered_date": "Delivered Date",
        "tracking_id": "Tracking ID",
        "beans_link": "Beans Tracking Lookup (View POD)",
        "compliant": "Marked as Compliant",
        "open_beans": "Open Beans POD",
        "kpi_title": "3) KPI Charts: Timeliness & Quality",
        "layout_mode_label": "KPI Layout Mode",
        "layout_mode_detailed": "Detailed (Week/Month)",
        "layout_mode_compact": "Compact (Day)",
        "compact_title": "24h DSP Assessment Metrics (Daily)",
        "daily_created_chart": "Daily package count by created date",
        "daily_eval_weight_chart": "Daily package evaluation weight",
        "weight_bucket_chart": "Weight bucket distribution",
        "compact_eval_weight": "Selected package evaluation weight",
        "eval_weight_empty": "No score data available",
        "kpi_empty": "No data available to calculate KPI.",
        "lost_detail": "Lost Package Details",
        "download_lost": "Download Lost Details",
        "download_delivered": "Download Delivery Rate Details",
        "download_dsp_detail": "Download DSP Details",
        "download_dsp_contractor_label": "Select Contractor",
        "download_dsp_contractor_placeholder": "Please select a contractor first",
        "download_dsp_requires_contractor": "You must select a contractor before downloading DSP details.",
        "download_dsp_empty": "No successfully delivered tracking numbers were found for this contractor in the selected date range.",
        "task_ready": "Ready to start…",
        "task_done": "Completed",
        "task_load_merge": "Load and Merge from DB",
        "task_compute_metrics": "Calculate Metrics",
        "task_prepare_dsp": "Prepare DSP Download",
        "task_step_assignee_cache": "Download and cache assignee list",
        "task_step_router_messages": "Load router_messages",
        "task_step_route_metadata": "Build route / assignee map",
        "task_step_receiver_data": "Load receiver address data",
        "task_step_sender_data": "Load sender address data",
        "task_step_tracking_rows": "Merge tracking result rows",
        "task_step_validate_filters": "Validate filters",
        "task_step_apply_filters": "Apply report date filter",
        "task_step_build_route_attempts": "Build route attempt details",
        "task_step_prepare_exports": "Prepare export datasets",
        "task_step_collect_dsp_price": "Load DSP price-related data",
        "task_step_build_dsp_file": "Build DSP Excel file",
        "download_dsp_prepare_btn": "Generate DSP detail file",
        "download_dsp_ready": "DSP detail file is ready. Click the button below to download it.",
        "download_scan": "Download Scan Rate Details",
        "lost_empty": "No waybills match the lost-package condition.",
        "lost_no_scan": "No Last Scan data, monthly lost-package rate cannot be calculated.",
    },
}
